version: 1
formatters:
  default:
    format: "%(asctime)s | %(levelname)s | %(name)s | %(message)s"
handlers:
  file:
    class: logging.FileHandler
    level: INFO
    formatter: default
    filename: prefect pipeline ochestration/datafiles/etl_pipeline_logs.txt
loggers:
  prefect:
    level: INFO
    handlers: [file]
